language: java

jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

before_script:

script:
  - ./gradlew build


after_script:
